/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package github.training;

public class App {
    public void startIntroduction() {
        System.out.println("Welcome to this Github Testbed! \nPlease introduce yourselves at the same time using GITHUB!");
        System.out.println("-----------------------------------------------");
    }


    /*
     * Each person should create an object of themselves with a basic sayGreeting method. 
     * Inside the listenForGreetingMethod(), they should call their sayGreetingMethod()
     */

    public void listenForGreetingMethod(){
        // Add your person with their sayGreeting() here. 
        new Yifan().sayGreeting();
    }


    public static void main(String[] args) {
        new App().startIntroduction(); 
        new App().listenForGreetingMethod();

    }
}
